# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

target 'myNFCatalog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myNFCatalog

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-nfc-manager', :path => '../node_modules/react-native-nfc-manager'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'myNFCatalogTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
